const nonEffectFusionMonsters = [
  "Amphibious Bugroth",
  "Aqua Dragon",
  "B. Skull Dragon",
  "Barox",
  "Bickuribox",
  "Blue-Eyes Ultimate Dragon",
  "Bracchio-raidus",
  "Charubin the Fire Knight",
  "Crimson Sunbird",
  "Cyber Saurus",
  "Darkfire Dragon",
  "Deepsea Shark",
  "Dragoness the Wicked Knight",
  "Empress Judge",
  "Flame Ghost",
  "Flame Swordsman",
  "Flower Wolf",
  "Fusionist",
  "Gaia the Dragon Champion",
  "Gem-Knight Zirconia",
  "Giltia the D. Knight",
  "Great Mammoth of Goldfine",
  "Humanoid Worm Drake",
  "Invoked Magellanica",
  "Kaiser Dragon",
  "Kaminari Attack",
  "Kamionwizard",
  "Karbonala Warrior",
  "Kwagar Hercules",
  "Labyrinth Tank",
  "Man-eating Black Shark",
  "Marine Beast",
  "Master of Oz",
  "Mavelus",
  "Metal Dragon",
  "Metalfoes Adamante",
  "Metalfoes Crimsonite",
  "Meteor B. Dragon",
  "Musician King",
  "Mystical Sand",
  "Pragtical",
  "Punished Eagle",
  "Rabid Horseman",
  "Rare Fish",
  "Roaring Ocean Snake",
  "Rose Spectre of Dunn",
  "Sanwitch",
  "Sea Monster of Theseus",
  "Skelgon",
  "Skull Knight",
  "Skullbird",
  "Soul Hunter",
  "St. Joan",
  "Steam Gyroid",
  "Thousand Dragon",
  "Twin-Headed Thunder Dragon",
  "Vermillion Sparrow",
  "Warrior of Tradition",
  "Zombie Warrior",
];

const nonEffectSynchroMonsters = [
  "Gaia Knight, the Force of Earth",
  "Naturia Leodrake",
  "Scrap Archfiend",
];

const questionMarkAtkMonsters = [
  "Aegaion the Sea Castrum",
  "Apollousa, Bow of the Goddess",
  "Ascension Sky Dragon",
  "Blackwing - Aurora the Northern Lights",
  "The Calculator",
  "Cell Division Token",
  "Chimeratech Overdragon",
  "Clear Vice Dragon",
  "Clone Dragon",
  "Clone Token",
  "Copy Token",
  "Cyber Eltanin",
  "Dark Soul Token",
  "Destiny HERO - Dreadmaster",
  "Divine Serpent Geh",
  "Doomsday Horror",
  "Doppelganger Token",
  "Drawler",
  "Duel Dragon Token",
  "Dyna Tank",
  "E'Rah Monster",
  "Eater of Millions",
  "Emissary of Darkness Token",
  "Endless Decay",
  "Evil Dragon Ananta",
  "Evil HERO Dark Gaia",
  "Exodia, the Legendary Defender",
  "Exodius the Ultimate Forbidden Lord",
  "Fire Wagon",
  "Fortune Lady Dark",
  "Fortune Lady Earth",
  "Fortune Lady Every",
  "Fortune Lady Fire",
  "Fortune Lady Light",
  "Fortune Lady Past",
  "Fortune Lady Water",
  "Fortune Lady Wind",
  "Gogogo Golem - Golden Form",
  "Gradius' Option",
  "Greed Quasar",
  "Gren Maju Da Eiza",
  "Half Token",
  "Helios - The Primordial Sun",
  "Helios Duo Megistus",
  "Helios Trice Megistus",
  "Holactie the Creator of Light",
  "Jormungandr, Generaider Boss of Eternity",
  "Kagemusha Raccoon Token",
  "Kasha",
  "King of the Skull Servants",
  "Kuribabylon",
  "The Legendary Exodia Incarnate",
  "Ma'at",
  "Maju Garzett",
  "Malus Token",
  "Manipulator Token",
  "Mask Token",
  "Megarock Dragon",
  "Metal Devil",
  "Mirage Token",
  "Montage Dragon",
  "Option Token",
  "Orichalcos Shunoros",
  "Parasitic Ticky",
  "Pilgrim Reaper",
  "Player Token",
  "Primal Being Token",
  "Rai-Jin",
  "Refraction Token",
  "Sample Fossil",
  "Scanner",
  "Selection Token",
  "Slifer the Sky Dragon",
  "Spirit Token",
  "Starduston",
  "Super Anti-Kaiju War Machine Mecha-Dogoran",
  "Ten Thousand Dragon",
  "Tenyi Spirit Token",
  "Timaeus the Knight of Destiny",
  "Tragoedia",
  "Tyranno Infinity",
  "UFOroid Fighter",
  "Umbral Horror Mirage Token",
  "Waltz Token",
  "The Wicked Avatar",
  "The Wicked Eraser",
  "The Winged Dragon of Ra",
  "The Winged Dragon of Ra - Sphere Mode",
  "Winged Kuriboh 9",
  "Winged Kuriboh LV9",
  "Worm Zero",
];

const questionMarkDefMonsters = [
  "Cell Division Token",
  "Chimeratech Overdragon",
  "Clone Dragon",
  "Clone Token",
  "Copy Token",
  "Cyber Eltanin",
  "Destiny HERO - Dreadmaster",
  "Doomsday Horror",
  "Doppelganger Token",
  "Drawler",
  "Duel Dragon Token",
  "E'Rah Monster",
  "Eater of Millions",
  "Emissary of Darkness Token",
  "Evil Dragon Ananta",
  "Exodia, the Legendary Defender",
  "Fortune Lady Dark",
  "Fortune Lady Earth",
  "Fortune Lady Every",
  "Fortune Lady Fire",
  "Fortune Lady Light",
  "Fortune Lady Past",
  "Fortune Lady Water",
  "Fortune Lady Wind",
  "Gradius' Option",
  "Greed Quasar",
  "Gren Maju Da Eiza",
  "Half Token",
  "Helios - The Primordial Sun",
  "Helios Duo Megistus",
  "Helios Trice Megistus",
  "Holactie the Creator of Light",
  "Jormungandr, Generaider Boss of Eternity",
  "Lost Guardian",
  "Ma'at",
  "Malus Token",
  "Manipulator Token",
  "Mask Token",
  "Megarock Dragon",
  "Mirage Token",
  "Option Token",
  "Orichalcos Aristeros",
  "Parasitic Ticky",
  "Pilgrim Reaper",
  "Player Token",
  "Primal Being Token",
  "Refraction Token",
  "Scanner",
  "Selection Token",
  "Slifer the Sky Dragon",
  "Spirit Token",
  "Starduston",
  "Ten Thousand Dragon",
  "Timaeus the Knight of Destiny",
  "Tragoedia",
  "UFOroid Fighter",
  "Waltz Token",
  "The Wicked Avatar",
  "The Wicked Eraser",
  "The Winged Dragon of Ra",
  "The Winged Dragon of Ra - Sphere Mode",
  "Winged Kuriboh 9",
  "Winged Kuriboh LV9",
];

module.exports = {
  nonEffectFusionMonsters,
  nonEffectSynchroMonsters,
  questionMarkAtkMonsters,
  questionMarkDefMonsters,
};
